runtime: python39
entrypoint: gunicorn -b :$PORT src.app:app
env: flex

runtime_config:
  python_version: 3

handlers:
- url: /static
  static_dir: src/static

- url: /models
  static_dir: models

- url: /data
  static_dir: data

- url: /.*
  script: auto