runtime: python39
entrypoint: gunicorn -b :$PORT src.app:app
handlers:
- url: /static
  static_dir: src/static

- url: /models
  static_dir: models

- url: /data
  static_dir: data

- url: /.*
  script: auto